apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: 19002256/goapp_gogetitdone:latest   
        ports: 
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret 
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret 
              key: db-password
        - name: DB_DIALECT
          valueFrom:
            secretKeyRef:
              name: app-secret 
              key: db-dialect
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-secret 
              key: db-host   
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config 
              key: DB_PORT
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: app-secret 
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config 
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret 
              key: redis-password                             