apiVersion: v1
kind: Secret
metadata: 
  name: app-secret
type: Opaque
data:
  pg-secrets: cG9zdGdyZXM=
  db-name: cG9zdGdyZXM=
  db-user: cG9zdGdyZXM=
  db-password: cG9zdGdyZXM= 
  db-dialect: cG9zdGdyZXM=

  db-host: cGctc3Zj
  redis-host: cmVkaXMtY2FjaGUtc3Zj
  
  redis-password: ""