apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
  labels: 
    app: pgdb
spec:
  serviceName: pg
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
    
      containers:
      - name: pg
        image: postgres:10.4
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: app-secret 
              key: pg-secrets
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secret 
              key: pg-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret 
              key: pg-secrets      
        
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pg-claim